services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $currentSeason: '%current_season%'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Menu}'
